import type { WidgetConfig } from './types';

const adminWidgets: WidgetConfig[] = [
  {
    id: 'admin-national-statistics',
    title: 'National Statistics',
    subtitle: 'Consolidated system-wide analytics',
    icon: 'TrendingUp',
    component: 'Statistic Card',
    size: 'small',
    priority: 1,
    permission: ['admin'],
    refreshInterval: 30,
  },
  {
    id: 'admin-live-incidents',
    title: 'Live Incidents',
    subtitle: 'National agency operational map',
    icon: 'Globe',
    component: 'Map',
    size: 'large',
    priority: 2,
    permission: ['admin'],
    refreshInterval: 5,
  },
  {
    id: 'admin-ai-intelligence',
    title: 'AI Intelligence',
    subtitle: 'Neural emergency scanning feeds telemetry',
    icon: 'BrainCircuit',
    component: 'AI Summary',
    size: 'wide',
    priority: 3,
    permission: ['admin'],
    refreshInterval: 15,
  },
  {
    id: 'admin-agency-performance',
    title: 'Agency Performance',
    subtitle: 'Police vs Medical vs NGO response rating',
    icon: 'Activity',
    component: 'Leaderboard',
    size: 'medium',
    priority: 4,
    permission: ['admin'],
    refreshInterval: 60,
  },
  {
    id: 'admin-response-time',
    title: 'Response Time',
    subtitle: 'Precinct mobilization speed pacing logs',
    icon: 'Zap',
    component: 'Chart',
    size: 'medium',
    priority: 5,
    permission: ['admin'],
    refreshInterval: 60,
  },
  {
    id: 'admin-resource-monitoring',
    title: 'Resource Monitoring',
    subtitle: 'Active dispatches units inventory count',
    icon: 'Shield',
    component: 'Gauge',
    size: 'small',
    priority: 6,
    permission: ['admin'],
    refreshInterval: 30,
  },
  {
    id: 'admin-system-health',
    title: 'System Health',
    subtitle: 'Supabase & API integrations status',
    icon: 'Cpu',
    component: 'Progress Card',
    size: 'small',
    priority: 7,
    permission: ['admin'],
    refreshInterval: 30,
  },
  {
    id: 'admin-audit-logs',
    title: 'Audit Logs',
    subtitle: 'Operational logs of database updates',
    icon: 'History',
    component: 'Activity Feed',
    size: 'medium',
    priority: 8,
    permission: ['admin'],
    refreshInterval: 10,
  },
];

export default adminWidgets;
