import type { WidgetConfig } from './types';

const childWelfareWidgets: WidgetConfig[] = [
  {
    id: 'welfare-awaiting-care',
    title: 'Children Awaiting Care',
    subtitle: 'Minors awaiting placement or reunion',
    icon: 'Baby',
    component: 'Statistic Card',
    size: 'small',
    priority: 1,
    permission: ['child_welfare'],
    refreshInterval: 10,
  },
  {
    id: 'welfare-shelters',
    title: 'Shelters',
    subtitle: 'Safehouses & verification centers map',
    icon: 'Building',
    component: 'Map',
    size: 'large',
    priority: 2,
    permission: ['child_welfare'],
    refreshInterval: 15,
  },
  {
    id: 'welfare-counselling',
    title: 'Counselling Sessions',
    subtitle: 'Active trauma support appointments',
    icon: 'Smile',
    component: 'Timeline',
    size: 'medium',
    priority: 3,
    permission: ['child_welfare'],
    refreshInterval: 30,
  },
  {
    id: 'welfare-verification',
    title: 'Guardian Verification',
    subtitle: 'Pending parent verification claims',
    icon: 'CheckSquare',
    component: 'Table',
    size: 'medium',
    priority: 4,
    permission: ['child_welfare'],
    refreshInterval: 10,
  },
  {
    id: 'welfare-legal-cases',
    title: 'Legal Cases',
    subtitle: 'Child protection custody custody files',
    icon: 'Briefcase',
    component: 'Table',
    size: 'medium',
    priority: 5,
    permission: ['child_welfare'],
    refreshInterval: 60,
  },
  {
    id: 'welfare-rehabilitation',
    title: 'Rehabilitation',
    subtitle: 'Reintegration process success rate',
    icon: 'HeartHandshake',
    component: 'Progress Card',
    size: 'small',
    priority: 6,
    permission: ['child_welfare'],
    refreshInterval: 30,
  },
  {
    id: 'welfare-pending-reviews',
    title: 'Pending Reviews',
    subtitle: 'Supervisor checklist workflow logs',
    icon: 'FileCheck',
    component: 'Activity Feed',
    size: 'medium',
    priority: 7,
    permission: ['child_welfare'],
    refreshInterval: 20,
  },
];

export default childWelfareWidgets;
