import type { WidgetConfig } from './types';

const citizenWidgets: WidgetConfig[] = [
  {
    id: 'citizen-ai-summary',
    title: 'Guardian AI Summary',
    subtitle: 'Emergency advisory scan matching analysis',
    icon: 'ShieldAlert',
    component: 'AI Summary',
    size: 'wide',
    priority: 1,
    permission: ['citizen'],
    refreshInterval: 15,
  },
  {
    id: 'citizen-active-reports',
    title: 'My Active Reports',
    subtitle: 'Timeline of submitted child logs',
    icon: 'FileText',
    component: 'Table',
    size: 'medium',
    priority: 2,
    permission: ['citizen'],
    refreshInterval: 10,
  },
  {
    id: 'citizen-emergency-contacts',
    title: 'Emergency Contacts',
    subtitle: 'Hotlines & welfare dispatch numbers',
    icon: 'PhoneCall',
    component: 'Quick Action',
    size: 'small',
    priority: 3,
    permission: ['citizen'],
    refreshInterval: 60,
  },
  {
    id: 'citizen-nearby-help',
    title: 'Nearby Help',
    subtitle: 'Volunteers and agencies in range',
    icon: 'MapPin',
    component: 'Map',
    size: 'large',
    priority: 4,
    permission: ['citizen'],
    refreshInterval: 5,
  },
  {
    id: 'citizen-rescue-status',
    title: 'Live Rescue Status',
    subtitle: 'Active responder tracking lifecycle',
    icon: 'Activity',
    component: 'Timeline',
    size: 'medium',
    priority: 5,
    permission: ['citizen'],
    refreshInterval: 5,
  },
  {
    id: 'citizen-notifications',
    title: 'Notifications',
    subtitle: 'Broadcast alerts & safety alerts',
    icon: 'Bell',
    component: 'Notification Panel',
    size: 'medium',
    priority: 6,
    permission: ['citizen'],
    refreshInterval: 3,
  },
  {
    id: 'citizen-quick-report',
    title: 'Quick Report',
    subtitle: 'One-tap emergency broadcast',
    icon: 'AlertTriangle',
    component: 'Quick Action',
    size: 'small',
    priority: 7,
    permission: ['citizen'],
    refreshInterval: 60,
  },
  {
    id: 'citizen-community-hero',
    title: 'Community Hero',
    subtitle: 'Verification & active scan score',
    icon: 'Award',
    component: 'Progress Card',
    size: 'small',
    priority: 8,
    permission: ['citizen'],
    refreshInterval: 30,
  },
];

export default citizenWidgets;
