import type { WidgetConfig } from './types';

const hospitalWidgets: WidgetConfig[] = [
  {
    id: 'hospital-incoming-patients',
    title: 'Incoming Patients',
    subtitle: 'Welfare ambulance triage arrivals',
    icon: 'Activity',
    component: 'Activity Feed',
    size: 'medium',
    priority: 1,
    permission: ['hospital'],
    refreshInterval: 5,
  },
  {
    id: 'hospital-emergency-beds',
    title: 'Emergency Beds',
    subtitle: 'Active trauma bed capacity',
    icon: 'Bed',
    component: 'Gauge',
    size: 'small',
    priority: 2,
    permission: ['hospital'],
    refreshInterval: 15,
  },
  {
    id: 'hospital-doctors-available',
    title: 'Doctors Available',
    subtitle: 'On-duty ER physicians roster',
    icon: 'HeartHandshake',
    component: 'Statistic Card',
    size: 'small',
    priority: 3,
    permission: ['hospital'],
    refreshInterval: 30,
  },
  {
    id: 'hospital-ambulances',
    title: 'Ambulances',
    subtitle: 'GPS tracking and ETAs',
    icon: 'Truck',
    component: 'Map',
    size: 'large',
    priority: 4,
    permission: ['hospital'],
    refreshInterval: 5,
  },
  {
    id: 'hospital-current-treatments',
    title: 'Current Treatments',
    subtitle: 'Stable case files details',
    icon: 'Clipboard',
    component: 'Table',
    size: 'medium',
    priority: 5,
    permission: ['hospital'],
    refreshInterval: 20,
  },
  {
    id: 'hospital-critical-cases',
    title: 'Critical Cases',
    subtitle: 'Trauma triage case count',
    icon: 'ShieldAlert',
    component: 'Statistic Card',
    size: 'small',
    priority: 6,
    permission: ['hospital'],
    refreshInterval: 10,
  },
  {
    id: 'hospital-medical-queue',
    title: 'Medical Queue',
    subtitle: 'Patients awaiting assessment',
    icon: 'Clock',
    component: 'Timeline',
    size: 'medium',
    priority: 7,
    permission: ['hospital'],
    refreshInterval: 5,
  },
  {
    id: 'hospital-capacity',
    title: 'Hospital Capacity',
    subtitle: 'Overall department occupancy rate',
    icon: 'Percent',
    component: 'Progress Card',
    size: 'small',
    priority: 8,
    permission: ['hospital'],
    refreshInterval: 30,
  },
];

export default hospitalWidgets;
