import type { WidgetConfig } from './types';

const ngoWidgets: WidgetConfig[] = [
  {
    id: 'ngo-shelter-capacity',
    title: 'Shelter Capacity',
    subtitle: 'Available beds at verified NGO facilities',
    icon: 'Home',
    component: 'Gauge',
    size: 'small',
    priority: 1,
    permission: ['ngo'],
    refreshInterval: 15,
  },
  {
    id: 'ngo-food-kits',
    title: 'Food Kits',
    subtitle: 'Ration bundles available in stock',
    icon: 'Apple',
    component: 'Progress Card',
    size: 'small',
    priority: 2,
    permission: ['ngo'],
    refreshInterval: 30,
  },
  {
    id: 'ngo-medical-kits',
    title: 'Medical Kits',
    subtitle: 'Emergency first aid supplies roster',
    icon: 'PlusCircle',
    component: 'Progress Card',
    size: 'small',
    priority: 3,
    permission: ['ngo'],
    refreshInterval: 30,
  },
  {
    id: 'ngo-volunteer-pool',
    title: 'Volunteer Pool',
    subtitle: 'Active members registered in shelter network',
    icon: 'Users',
    component: 'Statistic Card',
    size: 'small',
    priority: 4,
    permission: ['ngo'],
    refreshInterval: 30,
  },
  {
    id: 'ngo-resources',
    title: 'Resources',
    subtitle: 'Essential goods allocation chart',
    icon: 'PieChart',
    component: 'Chart',
    size: 'medium',
    priority: 5,
    permission: ['ngo'],
    refreshInterval: 60,
  },
  {
    id: 'ngo-current-missions',
    title: 'Current Missions',
    subtitle: 'Active support operations list',
    icon: 'Compass',
    component: 'Activity Feed',
    size: 'medium',
    priority: 6,
    permission: ['ngo'],
    refreshInterval: 10,
  },
  {
    id: 'ngo-families-supported',
    title: 'Families Supported',
    subtitle: 'Monthly rehabilitation case tracker',
    icon: 'Heart',
    component: 'Chart',
    size: 'medium',
    priority: 7,
    permission: ['ngo'],
    refreshInterval: 60,
  },
  {
    id: 'ngo-inventory',
    title: 'Inventory',
    subtitle: 'Detailed depot storage list',
    icon: 'Package',
    component: 'Table',
    size: 'medium',
    priority: 8,
    permission: ['ngo'],
    refreshInterval: 60,
  },
];

export default ngoWidgets;
