import type { WidgetConfig } from './types';

const policeWidgets: WidgetConfig[] = [
  {
    id: 'police-critical-cases',
    title: 'Critical Cases',
    subtitle: 'High priority active search reports',
    icon: 'AlertOctagon',
    component: 'Statistic Card',
    size: 'small',
    priority: 1,
    permission: ['police', 'admin'],
    refreshInterval: 10,
  },
  {
    id: 'police-dispatch-queue',
    title: 'Dispatch Queue',
    subtitle: 'Incidents awaiting field units',
    icon: 'Radio',
    component: 'Table',
    size: 'medium',
    priority: 2,
    permission: ['police'],
    refreshInterval: 5,
  },
  {
    id: 'police-available-officers',
    title: 'Available Officers',
    subtitle: 'Duty roster active unit stats',
    icon: 'UserCheck',
    component: 'Gauge',
    size: 'small',
    priority: 3,
    permission: ['police'],
    refreshInterval: 30,
  },
  {
    id: 'police-patrol-units',
    title: 'Patrol Units',
    subtitle: 'Real-time GPS tracker status map',
    icon: 'Navigation',
    component: 'Map',
    size: 'large',
    priority: 4,
    permission: ['police'],
    refreshInterval: 5,
  },
  {
    id: 'police-response-eta',
    title: 'Response ETA',
    subtitle: 'Avg dispatch mobilization speed',
    icon: 'Zap',
    component: 'Statistic Card',
    size: 'small',
    priority: 5,
    permission: ['police'],
    refreshInterval: 15,
  },
  {
    id: 'police-evidence',
    title: 'Evidence',
    subtitle: 'Photos and metadata details',
    icon: 'Camera',
    component: 'Table',
    size: 'medium',
    priority: 6,
    permission: ['police', 'admin'],
    refreshInterval: 30,
  },
  {
    id: 'police-live-operations',
    title: 'Live Operations',
    subtitle: 'Precinct activity feed log',
    icon: 'Sliders',
    component: 'Activity Feed',
    size: 'medium',
    priority: 7,
    permission: ['police'],
    refreshInterval: 3,
  },
  {
    id: 'police-emergency-heatmap',
    title: 'Emergency Heatmap',
    subtitle: 'Search zones concentration layout',
    icon: 'Flame',
    component: 'Map',
    size: 'large',
    priority: 8,
    permission: ['police', 'admin'],
    refreshInterval: 30,
  },
];

export default policeWidgets;
