import type { WidgetConfig } from './types';

const volunteerWidgets: WidgetConfig[] = [
  {
    id: 'volunteer-nearby-missions',
    title: 'Nearby Missions',
    subtitle: 'Search coordinates in your area',
    icon: 'Radar',
    component: 'Map',
    size: 'large',
    priority: 1,
    permission: ['volunteer'],
    refreshInterval: 5,
  },
  {
    id: 'volunteer-accepted-missions',
    title: 'Accepted Missions',
    subtitle: 'Assigned checklist items',
    icon: 'Bookmark',
    component: 'Timeline',
    size: 'medium',
    priority: 2,
    permission: ['volunteer'],
    refreshInterval: 5,
  },
  {
    id: 'volunteer-distance',
    title: 'Distance',
    subtitle: 'Target coordinate range',
    icon: 'Locate',
    component: 'Statistic Card',
    size: 'small',
    priority: 3,
    permission: ['volunteer'],
    refreshInterval: 5,
  },
  {
    id: 'volunteer-mission-progress',
    title: 'Mission Progress',
    subtitle: 'Verification task steps completed',
    icon: 'ChevronsUp',
    component: 'Progress Card',
    size: 'small',
    priority: 4,
    permission: ['volunteer'],
    refreshInterval: 10,
  },
  {
    id: 'volunteer-hero-points',
    title: 'Hero Points',
    subtitle: 'Total earned points in network',
    icon: 'Sparkles',
    component: 'Statistic Card',
    size: 'small',
    priority: 5,
    permission: ['volunteer'],
    refreshInterval: 30,
  },
  {
    id: 'volunteer-leaderboard',
    title: 'Leaderboard',
    subtitle: 'Top regional search volunteers',
    icon: 'ListOrdered',
    component: 'Leaderboard',
    size: 'medium',
    priority: 6,
    permission: ['volunteer'],
    refreshInterval: 60,
  },
  {
    id: 'volunteer-achievements',
    title: 'Achievements',
    subtitle: 'Unlocked badges & rescue milestones',
    icon: 'Award',
    component: 'Table',
    size: 'medium',
    priority: 7,
    permission: ['volunteer'],
    refreshInterval: 60,
  },
  {
    id: 'volunteer-hours-served',
    title: 'Hours Served',
    subtitle: 'Active search time tracking weekly',
    icon: 'History',
    component: 'Chart',
    size: 'medium',
    priority: 8,
    permission: ['volunteer'],
    refreshInterval: 60,
  },
];

export default volunteerWidgets;
